CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id        BIGSERIAL PRIMARY KEY,
    username  VARCHAR(255) UNIQUE NOT NULL,
    email     VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role      VARCHAR(50)  NOT NULL DEFAULT 'operator',
    is_active BOOLEAN      NOT NULL DEFAULT TRUE
);
